import { Badge, Button, Modal } from '../ds.js';
import { formatNaira } from '../mock/format.js';
import { downloadReceiptPdf } from './receiptPdf.js';
import styles from './Receipt.module.css';

/** On-screen receipt for a payout or a job's earnings (view model from domain/payouts.js). */
export function ReceiptView({ receipt }) {
  const company = receipt.company || {};
  return (
    <article className={styles.sheet} aria-label={`${receipt.kind} ${receipt.number}`}>
      <header className={styles.head}>
        <span><strong>TRUKKAS</strong><small>Move. Earn. Grow.</small></span>
        <span className={styles.kind}><strong>{receipt.kind}</strong><small>No. {receipt.number}</small></span>
      </header>
      <div className={styles.parties}>
        <div>
          <small className={styles.caps}>Issued to</small>
          <strong>{company.name}</strong>
          {[company.rcNumber, company.address, company.email].filter(Boolean).map((row) => <span key={row}>{row}</span>)}
        </div>
        <dl>
          {receipt.meta.map(([label, value, amount]) => (
            <div key={label}><dt>{label}</dt><dd>{label === 'Status' ? <Badge>{value}</Badge> : amount != null ? formatNaira(amount) : value}</dd></div>
          ))}
        </dl>
      </div>
      <table className={styles.table}>
        <thead><tr><th>Description</th><th>Amount</th></tr></thead>
        <tbody>
          {receipt.lines.length === 0 && <tr><td colSpan={2} className={styles.empty}>No delivered trips yet.</td></tr>}
          {receipt.lines.map((row) => (
            <tr key={row.description}>
              <td><strong>{row.description}</strong>{row.detail && <small>{row.detail}</small>}</td>
              <td>{formatNaira(row.amount)}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <dl className={styles.totals}>
        {receipt.totals.map((row) => (
          <div key={row.label} className={row.strong ? styles.strong : ''}><dt>{row.label}</dt><dd>{formatNaira(row.amount)}</dd></div>
        ))}
      </dl>
      {receipt.note && <p className={styles.note}>{receipt.note}</p>}
      <footer className={styles.foot}>Issued {receipt.issuedOn} · System-generated by the Trukkas platform; no signature required.</footer>
    </article>
  );
}

export function ReceiptModal({ receipt, open, onClose }) {
  if (!receipt) return null;
  return (
    <Modal
      open={open} onClose={onClose} width={720} title={receipt.kind} description={receipt.number}
      footer={<><Button variant="outline" onClick={onClose}>Close</Button><Button icon="download" onClick={() => downloadReceiptPdf(receipt)}>Download PDF</Button></>}
    >
      <ReceiptView receipt={receipt} />
    </Modal>
  );
}
